CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20250309180406_Initial') THEN
    CREATE TABLE races (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name text NOT NULL,
        date timestamp with time zone NOT NULL,
        distance_km numeric NOT NULL,
        CONSTRAINT pk_races PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20250309180406_Initial') THEN
    CREATE TABLE runners (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name text NOT NULL,
        email text NOT NULL,
        country text NOT NULL,
        CONSTRAINT pk_runners PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20250309180406_Initial') THEN
    CREATE TABLE race_result (
        runner_id integer NOT NULL,
        race_id integer NOT NULL,
        bib_number integer NOT NULL,
        position integer NOT NULL,
        time interval NOT NULL,
        CONSTRAINT pk_race_result PRIMARY KEY (runner_id, race_id),
        CONSTRAINT fk_race_result_races_race_id FOREIGN KEY (race_id) REFERENCES races (id) ON DELETE CASCADE,
        CONSTRAINT fk_race_result_runners_runner_id FOREIGN KEY (runner_id) REFERENCES runners (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20250309180406_Initial') THEN
    CREATE TABLE race_runner (
        races_id integer NOT NULL,
        runners_id integer NOT NULL,
        CONSTRAINT pk_race_runner PRIMARY KEY (races_id, runners_id),
        CONSTRAINT fk_race_runner_races_races_id FOREIGN KEY (races_id) REFERENCES races (id) ON DELETE CASCADE,
        CONSTRAINT fk_race_runner_runners_runners_id FOREIGN KEY (runners_id) REFERENCES runners (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20250309180406_Initial') THEN
    CREATE INDEX ix_race_result_bib_number ON race_result (bib_number);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20250309180406_Initial') THEN
    CREATE INDEX ix_race_result_race_id ON race_result (race_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20250309180406_Initial') THEN
    CREATE INDEX ix_race_runner_runners_id ON race_runner (runners_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20250309180406_Initial') THEN
    CREATE INDEX ix_races_date ON races (date);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20250309180406_Initial') THEN
    CREATE INDEX ix_runners_email ON runners (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20250309180406_Initial') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20250309180406_Initial', '9.0.2');
    END IF;
END $EF$;
COMMIT;

