version: '3.9'

# Use this spec during development

services:
  postgres:
    image: postgres:17-alpine
    shm_size: 2g
    cpu_count: 2
    user: root
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
